name: Flash Translation Layer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-x86_64:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: prepare environment
      run: |
        sudo apt-get update -y && sudo apt-get clean
        sudo apt-get install --no-install-recommends -y git make gcc g++ libglib2.0-dev libiberty-dev
        sudo apt-get install --no-install-recommends -y cppcheck flawfinder cflow
        sudo apt-get install --no-install-recommends -y python3-pip
        sudo pip3 install lizard==1.17.0
    - name: make check
      run: make check
    - name: make flow
      run: make flow
    - name: make
      run: make
    - name: make test
      run: make clean && make test USE_LOG_SILENT=1
    - name: make integration-test
      run: make clean && make integration-test
    - name: make benchmark.out
      run: make clean && make benchmark.out
  build-and-test-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pguyot/arm-runner-action@v2
        with:
          commands: |
            grep MemTotal /proc/meminfo
            sudo apt-get update -y && sudo apt-get clean
            sudo apt-get install --no-install-recommends -y git make gcc g++ libglib2.0-dev libiberty-dev
            sudo apt-get install --no-install-recommends -y cppcheck flawfinder cflow
            sudo apt-get install --no-install-recommends -y python3-pip
            sudo pip3 install lizard==1.17.0
            make check
            make flow
            make
            make clean && make test USE_LOG_SILENT=1
            make clean && make integration-test
            make clean && make benchmark.out
